"""Initial migration with roll column

Revision ID: cf37253ccb59
Revises: 
Create Date: 2025-03-22 00:42:57.263020

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'cf37253ccb59'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('användare',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('namn', sa.String(length=255), nullable=False),
    sa.Column('email', sa.String(length=255), nullable=False),
    sa.Column('lösenord_hash', sa.String(), nullable=False),
    sa.Column('roll', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('user_id'),
    sa.UniqueConstraint('email')
    )
    op.create_table('lag',
    sa.Column('lag_id', sa.Integer(), nullable=False),
    sa.Column('namn', sa.String(length=255), nullable=False),
    sa.Column('skapad_datum', sa.DateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=True),
    sa.PrimaryKeyConstraint('lag_id'),
    sa.UniqueConstraint('namn')
    )
    op.create_table('matcher',
    sa.Column('match_id', sa.Integer(), nullable=False),
    sa.Column('lag_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('plats', sa.String(length=255), nullable=False),
    sa.Column('motståndarlag', sa.String(length=255), nullable=False),
    sa.ForeignKeyConstraint(['lag_id'], ['lag.lag_id'], ),
    sa.PrimaryKeyConstraint('match_id')
    )
    op.create_table('träningar',
    sa.Column('träning_id', sa.Integer(), nullable=False),
    sa.Column('lag_id', sa.Integer(), nullable=False),
    sa.Column('datum', sa.DateTime(), nullable=False),
    sa.Column('typ', sa.String(length=100), nullable=False),
    sa.Column('närvaro', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['lag_id'], ['lag.lag_id'], ),
    sa.PrimaryKeyConstraint('träning_id')
    )
    op.create_table('user_lag',
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.Column('lag_id', sa.Integer(), nullable=False),
    sa.Column('roll', sa.String(length=50), nullable=False),
    sa.Column('position', sa.String(length=100), nullable=True),
    sa.ForeignKeyConstraint(['lag_id'], ['lag.lag_id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['användare.user_id'], ),
    sa.PrimaryKeyConstraint('user_id', 'lag_id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_lag')
    op.drop_table('träningar')
    op.drop_table('matcher')
    op.drop_table('lag')
    op.drop_table('användare')
    # ### end Alembic commands ###
